name: Distribute template updates
on:
  push:
    paths:
      - '.github/workflows/*'
      - '.github/default/*'

jobs:
  Get-repo-list:
    # Get repos that need to be updated 
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Find all workable repo
      id: repo_list
      uses: SFLScientific/fetch-repo-list@v1.2
      with:
        last_active: 90
        template: "bo-sfl/personal-template"
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}
        ignore_repos: "['SFLScientific/SFL-Template','SFLScientific/spellcheck-github-actions','SFLScientific/fetch-repo-list']" 

    - name: Pass repo list to output
      id: set-matrix
      run: |
        JSON="${{ steps.repo_list.outputs.repo_list }}"
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  Distribute-updates:
    needs: Get-repo-list
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.Get-repo-list.outputs.matrix)}}

    steps:
    - name: Fetch the template master
      uses: actions/checkout@master
      with:
        path: template
        lfs: False

    - name: Fetch the project repo master
      uses: actions/checkout@master
      with:
        path: project
        lfs: False
        repository: ${{ matrix.repo }}
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}

    - name: Populate changes
      run: |
        cp -r template/.github/workflows project/.github
        cp -r template/.github/default project/.github
           
    - name: Open a PR for updates
      uses: peter-evans/create-pull-request@v3.5.0
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: Fetch template Github Action updates
        committer: AutoCommit <${{ github.actor }}@users.noreply.github.com>
        title: Update Github Actions
        body: This is an auto-generated PR with most recent updated in template Github Actions.
        labels: Github-action-updates, automated pr
        branch: template-action-updates
        path: project
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}


