name: TODO and comment check
on: push
jobs:
  spelling:
    runs-on: ubuntu-latest
    if: ${{ (github.repository != 'SFLScientific/SFL-Template') }}
    steps:
    - uses: actions/checkout@v2
    - name: TODO and Commented out code status check
      uses: SFLScientific/TODOandCommentedCodeCheck@1.3

    
